
DROP TABLE IF EXISTS `{prefix}events`;

CREATE TABLE `{prefix}events` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`game_id` int(11) NOT NULL,
	`league_id` int(11) NOT NULL,
	`division_id` int(11) NOT NULL,
	`type` smallint(6) NOT NULL DEFAULT '0',
	`for` smallint(6) NOT NULL DEFAULT '0',
	`seed` smallint(6) NOT NULL DEFAULT '0',
	`round` smallint(6) DEFAULT NULL,
	`name` varchar(50) NOT NULL,
	`slug` varchar(50) NOT NULL,
	`start` datetime DEFAULT NULL,
	`end` datetime DEFAULT NULL,
	`signupStart` datetime DEFAULT NULL,
	`signupEnd` datetime DEFAULT NULL,
	`isRunning` tinyint(4) NOT NULL DEFAULT '0',
	`isFinished` tinyint(4) NOT NULL DEFAULT '0',
	`isGenerated` tinyint(4) NOT NULL DEFAULT '0',
	`requiredMembers` int(11) DEFAULT NULL,
	`maxParticipants` int(11) DEFAULT NULL,
	`maxRounds` int(11) DEFAULT NULL,
	`poolSize` int(11) DEFAULT NULL,
	`startingByes` int(11) DEFAULT NULL,
	`startingMatches` int(11) DEFAULT NULL,
	`bestOf` tinyint(4) NOT NULL DEFAULT '1',
	`pointsForWin` tinyint(4) NOT NULL DEFAULT '0',
	`pointsForLoss` tinyint(4) NOT NULL DEFAULT '0',
	`pointsForTie` tinyint(4) NOT NULL DEFAULT '0',
	`event_participant_count` int(11) NOT NULL DEFAULT '0',
	`match_count` int(11) NOT NULL DEFAULT '0',
	`created` datetime DEFAULT NULL,
	`modified` datetime DEFAULT NULL,
	PRIMARY KEY (`id`),
	KEY `game_id` (`game_id`),
	KEY `league_id` (`league_id`),
	KEY `division_id` (`division_id`),
	KEY `slug` (`slug`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
